version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestFeatureProject
  gitServerName: gitTest
  gitUrl: https://github.com/PoojaAnandGit/TestFeatureProject
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.testfeature.integrations:e1
  packages:
  - name: TestFeatureProject
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.843
