version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestFeatureProject
  gitServerName: gitTest
  gitUrl: https://github.com/PoojaAnandGit/TestFeatureProject
  gitUsername: PoojaAnandGit
  gitBranch: main
